### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by HunterBax** [nizeic/Noize#4]
 npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-10-06T02_49_33_667Z-debug.log
exit status 1
 
what is ?

**Comment by nizeic** [comment]
You're probably missing the `scripts` field in `package.json` (see lines 15-17 [here](https://github.com/nizeic/Noize/blob/main/package.json))

Also have you tried using `node index.js` instead of `npm start` to run the bot?

**Comment by HunterBax** [comment]
What is this error?
node index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/runner/test/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/test/node_modules/discord.js/src/index.js
- /home/runner/test/structures/client.js
- /home/runner/test/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/test/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/test/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/test/node_modules/discord.js/src/index.js',
    '/home/runner/test/structures/client.js',
    '/home/runner/test/index.js'
  ]
}
exit status 1

**Comment by HunterBax** [comment]
> You're probably missing the `scripts` field in `package.json` (see lines 15-17 [here](https://github.com/nizeic/Noize/blob/main/package.json))
> 
> Also have you tried using `node index.js` instead of `npm start` to run the bot?

No 
[replit.txt](https://github.com/nizeic/Noize/files/7290875/replit.txt)

**Comment by HunterBax** [comment]
![Uploading Untitled.png…]()

**Comment by nizeic** [comment]
in your `.replit` file, set `run` to `"npm start"`
![image](https://user-images.githubusercontent.com/48910077/136323518-b7a56ca2-0049-419b-885c-1482d61e78c8.png)

also make sure the `start` script in your `package.json` is set to `"node index.js"`
![image](https://user-images.githubusercontent.com/48910077/136323714-5e9a7eea-bba8-4adc-8c2c-df42d00adfdf.png)

**Comment by nizeic** [comment]
closing this due to inactivity. i added a note in the readme for replit users to update Node.

feel free to open a new issue if you still have problems with running the bot.
